### ISSUE TITLE
Thanks for implementing this! Couldn't get it to work, sadly.

### ISSUE THREAD

**Issue by eliot2** [philsmd/7z2hashcat#10]
Here's the command line of it tried your version 0.9 on hashcat 3.5 and 3.3:

https://pastebin.com/VDmSKkRT

Hashfile '.\returnHash.txt' on line 1 ( ■$): Signature unmatched
Hashfile '.\returnHash.txt' on line 2 (): Line-length exception

**Comment by philsmd** [comment]
Hello,

please consider giving a more meaningful name to github issues (so we can find it easily in the future)... just describe the issue (that's what the title is for).

I was able to reproduce this problem... but I am very sure this is neither a problem of hashcat, nor a problem of 7z2hashcat.

The problem here is that your shell (powershell) forces the output to be converted to UCS-2 LE BOM (by default). This is a type of encoding that hashcat doesn't support (it's also quite useless to convert it like this and makes no sense to support this strange encoding with so many additional bytes (which makes the files just larger and larger)).

I was able to use this to force ascii encoding:
```
.\7z2hashcat-0.9.exe .\test7crack.7z | Out-File -encoding ascii -force returnHash.txt
.\hashcat64.exe --m 11600 -a 3 --status-timer=20 -w 2 -i --increment-min 4 --increment-max 9 --runtime=10 1 ?l?u?d ?1?1?1?1?1?1?1?1?1  .\returnHash.txt
$7z$2$19$0$$8$36cec9d63a1f8ef00000000000000000$3819140844$16$12$6ea00e42d8ef0f9945ed163805ac9e3c$8$00:hijon
```

(Note: it makes no sense to use --increment-max 9 if you specify a much smaller mask, the length of the mask must at least be the value specified by increment-max)

So it works just fine. It also works with just cmd (out of the box, without conversion).

I don't think we could do anything more than this here... either you convert it to (ascii/utf8 without BOM yourself or you use the Out-File hack or you just use cmd.exe)
