### ISSUE TITLE
WARNING: the file 'test.7z' unfortunately can't be used with hashcat since the data length in this particular case is too long (1268976 of the maximum allowed 327528 bytes).

### ISSUE THREAD

**Issue by crecos** [philsmd/7z2hashcat#15]
[test.zip](https://github.com/philsmd/7z2hashcat/files/1518430/test.zip)

I attach the file where is test.7z

When I run 7z2hashcat I get output:

./7z2hashcat.pl test.7z
WARNING: the file 'test.7z' unfortunately can't be used with hashcat since the data length
in this particular case is too long (1268976 of the maximum allowed 327528 bytes).

Why?

Where is the error?

Thank you

**Comment by magnumripper** [comment]
Not a bug, it's an arbitrary limitation in hashcat. The (near identical) 7z2john.pl will create a hash but that hash is too long for hashcat to handle.

**Comment by crecos** [comment]
Thank you very much.

It is possible to modify the hashcat to support longer strings?

**Comment by philsmd** [comment]
It should be easy to increase the limit... I already explained a while ago how to do it e.g. here: https://hashcat.net/forum/thread-4328-post-33714.html#pid33714 (this might not be up-to-date with the current source code).

I don't think we can do anything here. It's a reasonable upper limit that hashcat uses and I think it makes sense to have such an upper limit. It's debatable if the limit is too low, but that could always be true. It could always be too low for somebody.
Some upper limit makes sense because of the line length parsing and output buffer and memory (pre-)allocation for the decompression etc.
It's also true that a non-random and non-binary file should normally not be larger in size than the upper limit set by hashcat if the file was heavily compressed, but this statement could also be false for some very large dictionary files etc

I don't think that this project (7z2hashcat) can do anything about this problem you are experiencing. The upper limit reported by 7z2hashcat is just in synch with what hashcat uses as upper limit. Only hashcat could increase the limit, but I'm not sure if that makes sense in general.

**Comment by crecos** [comment]
What is your paypal account? I would like to send donate for your time.
