### ISSUE TITLE
Null length of salt

### ISSUE THREAD

**Issue by Setplus01** [philsmd/7z2hashcat#16]
I 've run this programm on passworded 7zip file (without encryption of headers) and seen in output no salt and IV with 8 length. Is there no salt in 7zip file? An why length of IV is 8?

**Comment by philsmd** [comment]
This is perfectly normal. The 7-zip format (specification) would allow a custom salt and a longer salt, but both of these "features" are not widely used at all. pkzip and 7-Zip itself do not set a longer/shorter IV or a custom salt (by default) and therefore this is perfectly "normal".

If in doubt, you could just create a new 7-Zip file (with password) and try to crack it (and inspect the hash etc). It should crack of course ... and most likely it will also have a zero-length salt and a IV of 8 bytes.

I will close this issue because I don't think this is a real bug/problem.
Please reopen if you think this is not true and have problems cracking the hashes (for which you know the password and whose corresponding 7-zip file open with the password you are trying to crack the hash).
Thx

**Comment by Setplus01** [comment]
Thank you very much for your answer! I'll check in more details myself.
