### ISSUE TITLE
Size error

### ISSUE THREAD

**Issue by Sharkovichus** [philsmd/7z2hashcat#20]
Hello, thank you for your project!

I have a problem with  "7z2hashcat64-1.2.exe". 
Error text: "WARNING: the file 'archive.7z' unfortunately can't be used with hashcat since the data length in this particular case is too long (862336 of the maximum allowed 327528 bytes)"

What I have to do?

**Comment by philsmd** [comment]
hashcat (https://github.com/hashcat/hashcat) currently only allows a 7-Zip hash of 320KB or smaller.
In your case the hash is about 900KB long, which is much longer.

Several people had success modifying the 7z2hashcat and hashcat source code (at their own risk), see: https://hashcat.net/forum/thread-7446.html and https://hashcat.net/forum/thread-4328-post-33714.html#pid33714

It's not a problem of 7z2hashcat, but a limitation of hashcat (which is kind of reasonable, otherwise the RAM requirements with > 320KB would be much higher).
