### ISSUE TITLE
warning for particular case too long

### ISSUE THREAD

**Issue by thoreauzzy** [philsmd/7z2hashcat#22]
dear owner, when I try to crack the 7z files, I met the issue as follows.
WARNING: the file 'docu7.7z' unfortunately can't be used with hashca
t since the data length
in this particular case is too long (1702432 of the maximum allowed 327528 bytes).
would you help this problem? thx so much

**Comment by philsmd** [comment]
this problem is not really a 7z2hashcat problem, but a limitation in **hashcat** itself.

You are trying to crack a hash that is almost 2 MB big (or 4MB in hex). There are some limitations in hashcat, like the (hash) line length maximum and maximum byte size for compressed and decompressed length for 7z files.

I already explain this problem back then here: https://hashcat.net/forum/thread-4328-post-33714.html#pid33714 and the max size was increased already a couple of times to about 320 KB.
You can in theory patch hashcat to increase this limit as explained in the above post (the patch looks very slightly different today, because that post is over 2 years old) but of course there are some disadvantages when using much longer data (like the need for more RAM for all hash lines in general and the increased compressed and decompressed temporary byte buffers/memory etc).

Again, it's a limitation in hashcat itself and I my opinion is that it's not bad to have a limitation, but of course it could be handy sometimes if it was choosen a little bit higher (but again it has some side effects on the overall memory consumption, I think, for those very long hash lines > 1 MB etc).

**Comment by tp7309** [comment]
This is a limitation of hashcat, I also encountered the same problem and wrote a library [tt7zcrack](https://github.com/tp7309/tt7zcrack) to slove this problem(use some libraries), simpler configuration for crack 7z file.

@philsmd Thank you for create `7zhashcat` ^_^
