### ISSUE TITLE
bytes limit

### ISSUE THREAD

**Issue by teimes** [philsmd/7z2hashcat#23]
WARNING: the file '1.7z' unfortunately can't be used with hashcat since the data length
in this particular case is too long (6494176 of the maximum allowed 327528 bytes).

is it possile to fix dis som howe? xD
nise work on the program :)

**Comment by philsmd** [comment]
unfortunately it's a known limitation in the other project (hashcat , the password recovery tool). Your hash is about 6 MB huge . HUGE !

you would need to patch hashcat with all the disadvantages (more memory/RAM consumption, larger buffers etc).
You can just search for solution on the already closed issues here or on the hashcat github issue tracker (already dozens of issues closed with similar question) or on the hashcat forum

It's not a 7z2hashcat problem, but a problem of this particular algorithm which implies that a checksum of the whole data buffer must be computed. sometimes files are huge. Most often they are tiny, because.... surprise... compressed/archive files are small, in general.
