### ISSUE TITLE
possible to get hash of very large 7z file?

### ISSUE THREAD

**Issue by grahammitchell** [philsmd/7z2hashcat#28]
I created a very large encrypted 7z file (200+ GB) but lost the password. I was hoping to use 7z2hashcat but it just gives `Out of memory!`.

Then I tried using `dd` to create a smaller file from just the first 300KB, but 7z2hashcat just terminates with no output.

Am I out of luck?

Edit: I should add that my 7z archive only contains a single "file", a 200+ GB tarball. Looking at other issues/posts makes me think that might be relevant.

**Comment by philsmd** [comment]
yeah, it's not possible with 7z2hashcat + hashcat. They both have very strict limits (and are in sync with those limits).

I guess the best thing you could do is to try remember as much as possible from the password and try to build a very small dict and call the 7z tool in a loop or similar. I'm not sure if other tools support higher limits... There must always be some upper bound (hashcat has that limit especially because hash lines shouldn't be thaaaaat long and there is a generic limit of what the maximum size of a hash line should be).

In theory, you could change 7z2hashcat to not read these parts of the file into memory at all... but that doesn't help if no cracker (neither JTR nor hashcat etc) can deal with those "hashes".

I think you need to come up with a different approach here and most importantly try to think about the password and if it is even feasible to crack (i.e. remember how much you know about the password and if you could say it's for sure one of these password candidates from that - generated - dict  etc).

good luck

**Comment by grahammitchell** [comment]
Thanks for the reply. So do I correctly understand that the length of the hash is linear with the length of the (first) encrypted file in the 7z archive? That's surprising and I guess they're not really "hashes" in the usual sense.

Unfortunately for me, the password was generated using a tool and is pure random alphanumeric, so there's no wordlist that would be helpful other than [A-Za-z0-9].

Thanks again.

**Comment by philsmd** [comment]
yes, the CRC32 checksum of the decrypted and afterwards decompressed (if compressed) data is the only way to correctly verify that the password is the correct one (the chance that both decompression and crc32 checksum are working out with wrong data is very, very slim).

There is another way to attack these hashes: padding attacks. but hashcat doesn't use that attack anymore because of a lot of false positive reports for the 7z hash type. In your specific situation it could be something you could investigate (7z2hashcat has some hints in the source code of 7z2hashcat.pl about a padding attack, which was disabled for hashcat a long time ago). The hashcat forum also has some posts about the padding attack together with .7z files and which old hashcat versions supported this etc.

Of course, I can't really give much help with padding attacks here, because it's no more supported... maybe 7z2john.pl has enabled it (it's just a flag in 7z2hashcat/7z2john , 7z2john is basically the same code, just adapeted to the john format and cracker) and might still support padding attacks (risky, very dangerous if you do not understand the concept of false positives and if you can't interpret the output of the cracker correctly, most of the results are wrong !).

Yeah, it's very bad that it's random... maybe at least the length is not too long, otherwise I would really advise you to do the math and see if it's even feasible to crack within a few months/years (might take thousands of years if random and long). Please do the math !
