### ISSUE TITLE
not running in windows

### ISSUE THREAD

**Issue by nuhanbd** [philsmd/7z2hashcat#38]
I downloaded the exe but just cmd line occur then cmd closed.

**Comment by philsmd** [comment]
you need to open `cmd` and then navigate to your location with the `cd` command.

The problem is similar to this one mentioned for hashcat: https://hashcat.net/wiki/doku.php?id=frequently_asked_questions#why_does_a_window_pop_up_and_close_immediately

so you need to learn how to use terminal applications that run in `cmd` (without graphical user interface, `GUI`).

It's not that difficult. just place the exe in a convinient location and open `cmd` beforehand (no double click).

**Comment by philsmd** [comment]
Thanks to your (@nuhanbd ) suggestion / issue, I've now also added a note in the `README.md` file, see changes: https://github.com/philsmd/7z2hashcat/commit/2a041d9f1e784eae292d781165ed6f1c685f74b8
