### ISSUE TITLE
Unsupported methods emits an uncrackable $7z$0$ hash

### ISSUE THREAD

**Issue by magnumripper** [philsmd/7z2hashcat#7]
Create an archive using BCJ compression:
```
$ rm -f test.7z && 7z a test.7z -m0=bcj -pmagnum version.h
```

Current 7z2hashcat (hacked to never truncate) outputs this:
```
$ ../run/7z2john.pl test.7z
test.7z:$7z$0$19$0$$8$eaac88e57157a0800000000000000000$2955516664$48$44$ea50b56614201c62172e0f2ed75992e2463974007782cc83204a265443edaa9742fd54508696cfab510e9e996ec1d558

```

So the output suggests it's uncompressed. This is uncrackable (we'll get false negative) unless cracker *only* does a padding check.

Quick fix: For all unsupported compression types, output a `$7z$128` truncated hash if padding size is sufficient, otherwise warn/bail.

Long-term fix: Add support for all compression types with proper type field.

**Comment by magnumripper** [comment]
http://www.7-zip.org/7z.html

I guess we could simply establish these for our non-hash format:

| num | type |
| --- | ---- |
|0|uncompressed|
|1|LZMA|
|2|LZMA2|
|4|PPMD|
|8|BCJ|
|16|BCJ2|
|32|Bzip2|
|64|Deflate|
|128|Truncated|

OTOH we might use these instead, since they can't be combined anyway:

| num | type |
| --- | ---- |
|0|uncompressed|
|1|LZMA|
|2|LZMA2|
|3|PPMD|
|4|BCJ|
|5|BCJ2|
|6|Bzip2|
|7|Deflate|
|128|Truncated|

**Comment by philsmd** [comment]
It would be great if you could help me verify if the newest version and especially commit https://github.com/philsmd/7z2hashcat/commit/8ef8f21135e5e19bf9614355ef86d3dc248ad4e9 fixed this problem.
Thank you very much @magnumripper

**Comment by magnumripper** [comment]
At 7501caf1e it seems fine.

I do get this warning when running against a PPMD archive
```
$ ../run/7z2john.pl test.7z 
Use of uninitialized value in unpack at ../run/7z2john.pl line 1004.
test.7z:$7z$4$19$0$$8$eaac88e57157a0800000000000000000$2955516664$48$44$ea50b56614201c62172e0f2ed75992e2463974007782cc83204a265443edaa9742fd54508696cfab510e9e996ec1d558$44$
```
Considering the trailing `$` I guess the coder props is uninitialized and perhaps they are supposed to be empty. Perhaps just initialize it to a null string?

**Comment by philsmd** [comment]
I would suggest that whenever the attributes is not set, the output of 7z2hashcat should output an empty string (an empty field in this case).
I have pushed a fix for the uninitialized value error (see: https://github.com/philsmd/7z2hashcat/commit/5e0c03d88282f47b2b427f4f8a4657ae27997a44).

I think otherwise we tend to make the hash format too complicatd i.e. when we add another optional field whenever compression was used but no attributes are available (another special case that needs to be parsed by the crackers).

I think an empty field should be fine and it emphasizes that the attributes are empty (this can be noticed by a glance of the eyes, otherwise one could confuse the last field with the second last field etc).

I think the empty last field in those rare cases should be okay. This should only happen whenever the crackers need to use decompression and in addition to that only when a rare (non-LZMA1/non-LZMA2) compressor was used.
Do you think this is acceptable like this?

**Comment by magnumripper** [comment]
Sure, that's very sound reasoning. Thanks!
